# Diskritisasi


1. Carilah data yang bertipe numerik ( data klassifikasi)
2. Lakukan proses diskritisasi dengan *equal width* dan *equal frequency*
3. Lakukan proses diskritisasi dengan basis *entropy*
4. Kumpulkan tugas dengan link github ( web statis dari jupyter book)


## Data

In [ ]:
# mengimpor paket pandas kemudian diberi nama alias pd
import pandas as pd
# mengimpor paket seaborn kemudian diberi nama alias sns
import seaborn as sns
# mengimpor paket numpy kemudian diberi nama alias np
import numpy as np
# mengimpor paket sklearn kemudian diberi nama alias sk
import sklearn as sk
# modul untuk menghitung logaritma
from math import log2

In [ ]:
# source data
iris = pd.read_csv("https://raw.githubusercontent.com/rizkyluxszerr/datamining/main/iris_csv.csv")

In [ ]:
#menampilkan data
iris

     sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
# CONSTAN SERIES

SEPAL_LENGTH_SERIES = iris["sepallength"]
SEPAL_WIDTH_SERIES = iris["sepalwidth"]
PETAL_LENGTH_SERIES = iris["petallength"]
PETAL_WIDTH_SERIES = iris["petalwidth"]

## Hitung Data

### Definisi *discretization*

Discretization atau binning digunakan untuk mengubah atribut numerik menjadi atribut kategorikal. Perubahan tersebut dilakukan dengan mengkategorikan atribut numerik menjadi beberapa tingkatan atribut kategorikal

#### Cut

* Cut adalah sebuah *method* pada library *pandas* untuk melakukan perhitungan *equal width frequency intervals*


```
# Syntax
pd.cut(series, interval, right=True, label)
```

##### Sepal Width

* Equal Width Intervals lebar kelopak bunga Iris Dikelompokkan menjadi 3 kategori yaitu

1.   Kategori sedikit lebar
2.   Kategori lebar
3.   Kategori sangat lebar

In [ ]:
# equal-width intervals

labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(labels)

sepal_width_ew_binning = pd.cut(SEPAL_WIDTH_SERIES, amount_of_binning, True, labels)
labelled_sepal_width_ew_binning = sepal_width_ew_binning.value_counts()
interval_sepal_width_ew_binning = pd.cut(SEPAL_WIDTH_SERIES, amount_of_binning, True).value_counts()

In [ ]:
# dataframe of sepal-width and sepal category
df_sepal_width_ew = pd.DataFrame(pd.concat((SEPAL_WIDTH_SERIES, sepal_width_ew_binning), axis=1))

In [ ]:
# change columns name
df_sepal_width_ew.columns = ["sepal.width", "category"]

In [ ]:
df_sepal_width_ew

     sepal.width       category
0            3.5          lebar
1            3.0          lebar
2            3.2          lebar
3            3.1          lebar
4            3.6          lebar
..           ...            ...
145          3.0          lebar
146          2.5  sedikit_lebar
147          3.0          lebar
148          3.4          lebar
149          3.0          lebar

[150 rows x 2 columns]

In [ ]:
# equal-width intervals binning with label
labelled_sepal_width_ew_binning

lebar            88
sedikit_lebar    47
sangat_lebar     15
Name: sepalwidth, dtype: int64

In [ ]:
# equal-width intervals without label
interval_sepal_width_ew_binning

(2.8, 3.6]      88
(1.998, 2.8]    47
(3.6, 4.4]      15
Name: sepalwidth, dtype: int64

##### Petal Width

Equal Width Intervals lebar kelopak bunga Iris Dikelompokkan menjadi 3 kategori yaitu

1.   Kategori sedikit lebar
2.   Kategori lebar
3.   Kategori sangat lebar

In [ ]:
# equal-width intervals
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(labels)

petal_width_ew_binning = pd.cut(PETAL_WIDTH_SERIES, amount_of_binning, True, labels)
labelled_petal_width_ew_binning = petal_width_ew_binning.value_counts()
interval_petal_width_ew_binning = pd.cut(PETAL_WIDTH_SERIES, amount_of_binning, True).value_counts()

In [ ]:
# dataframe of petal-width and petal category
df_petal_width = pd.DataFrame(pd.concat((PETAL_WIDTH_SERIES, petal_width_ew_binning), axis=1))

In [ ]:
# change columns name
df_petal_width.columns = ["petal.width", "category"]

In [ ]:
df_petal_width

     petal.width       category
0            0.2  sedikit_lebar
1            0.2  sedikit_lebar
2            0.2  sedikit_lebar
3            0.2  sedikit_lebar
4            0.2  sedikit_lebar
..           ...            ...
145          2.3   sangat_lebar
146          1.9   sangat_lebar
147          2.0   sangat_lebar
148          2.3   sangat_lebar
149          1.8   sangat_lebar

[150 rows x 2 columns]

In [ ]:
# equal-width intervals with label
labelled_petal_width_ew_binning

lebar            54
sedikit_lebar    50
sangat_lebar     46
Name: petal.width, dtype: int64

In [ ]:
# equal-width intervals without label
interval_petal_width_ew_binning

(0.9, 1.7]       54
(0.0976, 0.9]    50
(1.7, 2.5]       46
Name: petal.width, dtype: int64

##### Sepal Length

Equal Width Intervals lebar kelopak bunga Iris Dikelompokkan menjadi 3 kategori yaitu

1.   Kategori sedikit lebar
2.   Kategori lebar
3.   Kategori sangat lebar

In [ ]:
# equal-width intervals

labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(labels)

sepal_length_ew_binning = pd.cut(SEPAL_LENGTH_SERIES, amount_of_binning, True, labels)
labelled_sepal_length_ew_binning = sepal_length_ew_binning.value_counts()
interval_sepal_length_ew_binning = pd.cut(SEPAL_LENGTH_SERIES, amount_of_binning, True).value_counts()

In [ ]:
# dataframe of sepal-width and sepal category
df_sepal_length_ew = pd.DataFrame(pd.concat((SEPAL_LENGTH_SERIES, sepal_length_ew_binning), axis=1))

In [ ]:
# change columns name
df_sepal_length_ew.columns = ["sepal_length", "category"]

In [ ]:
df_sepal_length_ew

     sepal_length       category
0             5.1  sedikit_lebar
1             4.9  sedikit_lebar
2             4.7  sedikit_lebar
3             4.6  sedikit_lebar
4             5.0  sedikit_lebar
..            ...            ...
145           6.7          lebar
146           6.3          lebar
147           6.5          lebar
148           6.2          lebar
149           5.9          lebar

[150 rows x 2 columns]

In [ ]:
# equal-width intervals with label
labelled_sepal_length_ew_binning

lebar            71
sedikit_lebar    59
sangat_lebar     20
Name: sepal.length, dtype: int64

In [ ]:
# equal-width intervals without label
interval_sepal_length_ew_binning

(5.5, 6.7]      71
(4.296, 5.5]    59
(6.7, 7.9]      20
Name: sepal.length, dtype: int64

##### Petal Length

Equal Width Intervals lebar kelopak bunga Iris Dikelompokkan menjadi 3 kategori yaitu

1.   Kategori sedikit lebar
2.   Kategori lebar
3.   Kategori sangat lebar

In [ ]:
# equal-width intervals
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(labels)

petal_length_ew_binning = pd.cut(PETAL_LENGTH_SERIES, amount_of_binning, True, labels)
labelled_petal_length_ew_binning = petal_length_ew_binning.value_counts()
interval_petal_length_ew_binning = pd.cut(PETAL_LENGTH_SERIES, amount_of_binning, True).value_counts()

In [ ]:
# dataframe of petal-width and petal category
df_petal_length_ew =  pd.DataFrame(pd.concat((PETAL_LENGTH_SERIES,petal_length_ew_binning), axis=1))

In [ ]:
# change columns name
df_petal_length_ew.columns = ["petal_length", "category"]

In [ ]:
df_petal_length_ew

     petal_length       category
0             1.4  sedikit_lebar
1             1.4  sedikit_lebar
2             1.3  sedikit_lebar
3             1.5  sedikit_lebar
4             1.4  sedikit_lebar
..            ...            ...
145           5.2   sangat_lebar
146           5.0   sangat_lebar
147           5.2   sangat_lebar
148           5.4   sangat_lebar
149           5.1   sangat_lebar

[150 rows x 2 columns]

In [ ]:
# equal-width intervals binning with label
labelled_petal_length_ew_binning

lebar            54
sedikit_lebar    50
sangat_lebar     46
Name: petallength, dtype: int64

In [ ]:
# equal-width intervals out label
interval_petal_length_ew_binning

(2.967, 4.933]    54
(0.994, 2.967]    50
(4.933, 6.9]      46
Name: petallength, dtype: int64

#### Qcut
* Qcut adalah sebuah *method* pada library *pandas* untuk melakukan perhitungan *equal frequency intervals*

```
# Syntax
pd.qcut(series, interval, label)
```

##### Sepal Width

Equal Width Intervals lebar kelopak bunga Iris Dikelompokkan menjadi 3 kategori yaitu

1.   Kategori sedikit lebar
2.   Kategori lebar
3.   Kategori sangat lebar

In [ ]:
# equal-frequency intervals

labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(labels)

sepal_width_ef_binning = pd.qcut(SEPAL_WIDTH_SERIES, amount_of_binning, labels)
labelled_sepal_width_ef_binning = sepal_width_ef_binning.value_counts()
interval_sepal_width_ef_binning = pd.qcut(SEPAL_WIDTH_SERIES, amount_of_binning).value_counts()

In [ ]:
# dataframe of sepal-width and sepal category
df_sepal_width_ef = pd.DataFrame(pd.concat((SEPAL_WIDTH_SERIES, sepal_width_ef_binning), axis = 1))

In [ ]:
# change columns name
df_sepal_width_ef.columns = ["sepal_width", "category"]

In [ ]:
df_sepal_width_ef

     sepal_width       category
0            3.5   sangat_lebar
1            3.0          lebar
2            3.2          lebar
3            3.1          lebar
4            3.6   sangat_lebar
..           ...            ...
145          3.0          lebar
146          2.5  sedikit_lebar
147          3.0          lebar
148          3.4   sangat_lebar
149          3.0          lebar

[150 rows x 2 columns]

In [ ]:
# equal-frequency intervals binning with label
labelled_sepal_width_ef_binning

sedikit_lebar    57
lebar            51
sangat_lebar     42
Name: sepalwidth, dtype: int64

In [ ]:
# equal-frequency intervals out label
interval_sepal_width_ef_binning

(1.999, 2.9]    57
(2.9, 3.2]      51
(3.2, 4.4]      42
Name: sepalwidth, dtype: int64

##### Petal Width

Equal Width Intervals lebar kelopak bunga Iris Dikelompokkan menjadi 3 kategori yaitu

1.   Kategori sedikit lebar
2.   Kategori lebar
3.   Kategori sangat lebar

In [ ]:
# equal-frequency intervals

labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(labels)

petal_width_ef_binning = pd.qcut(PETAL_WIDTH_SERIES, amount_of_binning, labels)
labelled_petal_width_ef_binning = petal_width_ef_binning.value_counts()
interval_petal_width_ef_binning = pd.qcut(PETAL_WIDTH_SERIES, amount_of_binning).value_counts()

In [ ]:
# dataframe of petal-width and petal category
df_petal_width_ef = pd.DataFrame(pd.concat((PETAL_WIDTH_SERIES, petal_width_ef_binning), axis = 1))

In [ ]:
# change columns name
df_petal_width_ef.columns = ["petal_width", "category"]

In [ ]:
df_petal_width_ef

     petal_width       category
0            0.2  sedikit_lebar
1            0.2  sedikit_lebar
2            0.2  sedikit_lebar
3            0.2  sedikit_lebar
4            0.2  sedikit_lebar
..           ...            ...
145          2.3   sangat_lebar
146          1.9   sangat_lebar
147          2.0   sangat_lebar
148          2.3   sangat_lebar
149          1.8   sangat_lebar

[150 rows x 2 columns]

In [ ]:
# equal-frequency intervals binning with label
labelled_petal_width_ef_binning

lebar            52
sedikit_lebar    50
sangat_lebar     48
Name: petalwidth, dtype: int64

In [ ]:
# equal-frequency intervals without label
interval_petal_width_ef_binning

(0.867, 1.6]      52
(0.099, 0.867]    50
(1.6, 2.5]        48
Name: petalwidth, dtype: int64

##### Sepal Length

Equal Width Intervals lebar kelopak bunga Iris Dikelompokkan menjadi 3 kategori yaitu

1.   Kategori sedikit lebar
2.   Kategori lebar
3.   Kategori sangat lebar

In [ ]:
# equal-frequency intervals

labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(labels)

sepal_length_ef_binning = pd.qcut(SEPAL_LENGTH_SERIES, amount_of_binning, labels)
labelled_sepal_length_ef_binning = sepal_length_ef_binning.value_counts()
interval_sepal_length_ef_binning = pd.qcut(SEPAL_LENGTH_SERIES, amount_of_binning).value_counts()

In [ ]:
# dataframe of sepal-length and sepal category
df_sepal_length_ef = pd.DataFrame(pd.concat((SEPAL_LENGTH_SERIES, sepal_length_ef_binning), axis=1))

In [ ]:
# change columns name
df_sepal_length_ef.columns = ["sepal_length", "category"]

In [ ]:
df_sepal_length_ef

     sepal_length       category
0             5.1  sedikit_lebar
1             4.9  sedikit_lebar
2             4.7  sedikit_lebar
3             4.6  sedikit_lebar
4             5.0  sedikit_lebar
..            ...            ...
145           6.7   sangat_lebar
146           6.3          lebar
147           6.5   sangat_lebar
148           6.2          lebar
149           5.9          lebar

[150 rows x 2 columns]

In [ ]:
# equal-frequency intervals binning with label
labelled_sepal_length_ef_binning

lebar            56
sedikit_lebar    52
sangat_lebar     42
Name: sepallength, dtype: int64

In [ ]:
# equal-frequency intervals out label
interval_sepal_length_ef_binning

(5.4, 6.3]                   56
(4.2989999999999995, 5.4]    52
(6.3, 7.9]                   42
Name: sepallength, dtype: int64

##### Petal Length

Equal Width Intervals lebar kelopak bunga Iris Dikelompokkan menjadi 3 kategori yaitu

1.   Kategori sedikit lebar
2.   Kategori lebar
3.   Kategori sangat lebar

In [ ]:
# equal-frequency intervals

labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(labels)

petal_length_ef_binning = pd.qcut(PETAL_LENGTH_SERIES, amount_of_binning, labels)
labelled_petal_length_ef_binning = petal_length_ef_binning.value_counts()
interval_petal_length_ef_binning = pd.qcut(PETAL_LENGTH_SERIES, amount_of_binning).value_counts()

In [ ]:
# dataframe of petal-length and petal category
df_petal_length_ef = pd.DataFrame(pd.concat((PETAL_LENGTH_SERIES, petal_length_ef_binning), axis=1))

In [ ]:
# change columns name
df_petal_length_ef.columns = ["petal_length", "category"]

In [ ]:
df_petal_length_ef

     petal_length       category
0             1.4  sedikit_lebar
1             1.4  sedikit_lebar
2             1.3  sedikit_lebar
3             1.5  sedikit_lebar
4             1.4  sedikit_lebar
..            ...            ...
145           5.2   sangat_lebar
146           5.0   sangat_lebar
147           5.2   sangat_lebar
148           5.4   sangat_lebar
149           5.1   sangat_lebar

[150 rows x 2 columns]

In [ ]:
# equal-frequency intervals binning with label
labelled_petal_length_ef_binning

lebar            54
sedikit_lebar    50
sangat_lebar     46
Name: petallength, dtype: int64

In [ ]:
# equal-frequency intervals out label
interval_petal_length_ef_binning

(2.633, 4.9]      54
(0.999, 2.633]    50
(4.9, 6.9]        46
Name: petallength, dtype: int64

### Definisi Entropy-based Binning

1.   Metode untuk mengelompokkan data *numeric* menjadi *categorical*
2.   Pengelompokkan dengan mencari jumlah pembagi yang terabaik
3.   Hasil pengelompokkan terbaik adalah dengan *entropy gain* yang paling besar


*  Rumus Entropy

$$
\begin{align*}
\displaystyle Entropy(S) &= \sum_{i=0}^{k} -pi \ log_{2} \ pi \\
\end{align*}
$$

#### Persiapan


*   Impor modul log2 dari *package math*
*   Ambil data yang akan digunakan


```
# dataframe about petal width (Equeal Frequency Interval)
df_petal_width_ef
```

*  Tentukan label


```
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
```

In [ ]:
# dataframe
target_data = df_petal_width_ef
target_data

     petal_width       category
0            0.2  sedikit_lebar
1            0.2  sedikit_lebar
2            0.2  sedikit_lebar
3            0.2  sedikit_lebar
4            0.2  sedikit_lebar
..           ...            ...
145          2.3   sangat_lebar
146          1.9   sangat_lebar
147          2.0   sangat_lebar
148          2.3   sangat_lebar
149          1.8   sangat_lebar

[150 rows x 2 columns]

In [ ]:
# category label
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]

##### Functions

###### Fungsi menghitung banyaknya data setiap kategori

In [ ]:
# count every value based the given category
def countEveryCategory(data_column, labels, column, category):
    group = data_column.groupby(category).count()
    amount_of_every_category = []
    for label in labels:
        amount_of_every_category.append(group.loc[label, column])
    return amount_of_every_category

###### Fungsi menghitung banyaknya data setiap kategori berdasarkan nilai pembagi atau *split value* yang diberikan

In [ ]:
# split the given data based on category and split value 
def split(split_value, data_column, labels, col, category):
    less_group = data_column[data_column[col] < split_value]
    greater_group = data_column[data_column[col] >= split_value]
    
    length_less_group = countEveryCategory(less_group, labels, col, category)
    length_greater_group = countEveryCategory(greater_group, labels, col, category)
    
    return (length_less_group, length_greater_group)

###### Fungsi menghitung perbedaan *gain* antara entropi inisial dengan entropi nilai pembagi yang diberikan




---
$$Gain(E_{new}) = (E_{initial}) \ - (E_{new})$$
---

In [ ]:
# count information gain from inisial entropy and new entropy
def count_gain(inisial_entropy, new_entropy):
  return inisial_entropy - new_entropy

###### Fungsi menghitung entropy

In [ ]:
# count entropy
def count_entropy(data_target):
    all_prob = []
    for prob in data_target:
        if (prob/sum(data_target) != 0):
            all_prob.append(prob/sum(data_target) * log2(prob/sum(data_target)))
        else:
            all_prob.append(0)
    return -(sum(all_prob))

###### Fungsi menghitung Info entropy berdasarkan nilai pembagi atau *split value* yang diberikan


---



$$ Info_A(D) = \frac{|D_1|}{|D|} Entropy (D_1)\frac{|D_2|}{|D|}+ Entropy (D_2)$$

In [ ]:
# count entropy for given a split value
def info(d, data_target):
    temp = []
    for value in d:
        temp.append((sum(value) / data_target.shape[0]) * count_entropy(value))
    return sum(temp)

###### Implementasi


*   Hitung target *entropy*
*   Hitung target *entropy* dengan *split value*
*   Hitung *entropy gain*

In [ ]:
# entropy data target
initial_data_target_entropy = count_entropy(countEveryCategory(target_data, labels, target_data.columns[0], target_data.columns[1]))

In [ ]:
# count Entropy for the target given a split value, split value = 0.7
entropy_data_target_1 = info(split(0.7, target_data, labels, target_data.columns[0], target_data.columns[1]), target_data)

In [ ]:
# information gain (entropy data target and entropy_data_target_1)
count_gain(initial_data_target_entropy, entropy_data_target_1)

0.9182958340544896